<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>False</UseWPF>
    <StartupObject>SewingProduction.Core.Program</StartupObject>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <ApplicationIcon>Resources\AppIcons\favicon.ico</ApplicationIcon>
    <SignAssembly>False</SignAssembly>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\KnittingProduction\Models\KnitMachineLoadInfo - Копировать.cs" />
    <Compile Remove="Features\Settings.cs" />
    <Compile Remove="Features\Settings.Designer.cs" />
    <Compile Remove="Features\TeamWork\Forms\TeamWork.WorkDivisions1.cs" />
    <Compile Remove="Features\TeamWork\Helpers\ANNGridViewHelper.cs" />
    <Compile Remove="Features\TeamWork\Helpers\AnnManager.cs" />
    <Compile Remove="Features\TeamWork\Helpers\ArtNormController.cs" />
    <Compile Remove="Features\TeamWork\Helpers\NormRaskManager.cs" />
    <Compile Remove="Features\TeamWork\Helpers\NormRaszManager.cs" />
    <Compile Remove="Features\TeamWork\Models\NormRasz1.cs" />
    <Compile Remove="Features\TeamWork\Models\NormRasz2.cs" />
    <Compile Remove="Report\PostReportFio.cs" />
    <Compile Remove="Report\PostReportFio.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Core\Class\CustomControls.resx" />
    <EmbeddedResource Remove="Report\PostReportFio.resx" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Features\TeamWork.zip" />
    <None Remove="Features\TeamWork\Forms\исходная НАДИНА SQL процедура .txt" />
    <None Remove="Help\Features\TeamWork\Forms\img\1.png" />
    <None Remove="Help\Features\TeamWork\Forms\img\10.png" />
    <None Remove="Help\Features\TeamWork\Forms\img\11.png" />
    <None Remove="Help\Features\TeamWork\Forms\img\12.png" />
    <None Remove="Help\Features\TeamWork\Forms\img\13.png" />
    <None Remove="Help\Features\TeamWork\Forms\img\14.png" />
    <None Remove="Help\Features\TeamWork\Forms\img\2.png" />
    <None Remove="Help\Features\TeamWork\Forms\img\3.png" />
    <None Remove="Help\Features\TeamWork\Forms\img\4.png" />
    <None Remove="Help\Features\TeamWork\Forms\img\5.png" />
    <None Remove="Help\Features\TeamWork\Forms\img\6.png" />
    <None Remove="Help\Features\TeamWork\Forms\img\7.png" />
    <None Remove="Help\Features\TeamWork\Forms\img\8.png" />
    <None Remove="Help\Features\TeamWork\Forms\img\9.png" />
    <None Remove="Help\Features\TeamWork\Forms\TeamWork.html" />
    <None Remove="Help\Features\UserDistribution\Forms\ActionHistory.html" />
    <None Remove="Help\Features\UserDistribution\Forms\AdminForm.html" />
    <None Remove="Help\Features\UserDistribution\Forms\AllRole.html" />
    <None Remove="Help\Features\UserDistribution\Forms\AllUser.html" />
    <None Remove="Help\Features\UserDistribution\Forms\Dictionary.html" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\ActionHistory.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\AdminForm.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\AllRole-SetForm.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\AllRole-SetUser.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\AllRole.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\AllUser-AddUser.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\AllUser-AddUser2.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\AllUser-SetRole.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\AllUser.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\Dictionary-add.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\Dictionary-add2.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\Dictionary.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\RoleColumn.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\RoleColumnY.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\Settings.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\UserHierarchy.png" />
    <None Remove="Help\Features\UserDistribution\Forms\Img\UserProfile.png" />
    <None Remove="Help\Features\UserDistribution\Forms\RoleColumn.html" />
    <None Remove="Help\Features\UserDistribution\Forms\Settings.html" />
    <None Remove="Help\Features\UserDistribution\Forms\UserHierarchy.html" />
    <None Remove="Help\Features\UserDistribution\Forms\UserProfile.html" />
    <None Remove="Help\Help.html" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Help\Features\TeamWork\Forms\img\1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\10.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\11.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\12.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\13.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\14.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\7.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\8.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\9.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\TeamWork.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\AllRole.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Help\Features\UserDistribution\Forms\ActionHistory.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\AdminForm.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\AllUser.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Dictionary.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\ActionHistory.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AdminForm.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AllRole-SetForm.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AllRole-SetUser.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AllRole.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AllUser-AddUser.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AllUser-AddUser2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AllUser-SetRole.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AllUser.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\Dictionary-add.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\Dictionary-add2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\Dictionary.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\RoleColumn.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\RoleColumnY.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\Settings.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\UserHierarchy.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\UserProfile.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\RoleColumn.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Settings.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\UserHierarchy.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\UserProfile.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Help.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AppIcons\favicon.ico" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.1" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="DevExpress.Win.Design" Version="24.2.7" />
    <PackageReference Include="Microsoft.AspNet.Identity.Core" Version="2.2.4" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.6" />
    <PackageReference Include="Microsoft.ReportingServices.ReportViewerControl.WebForms" Version="150.1652.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NLog" Version="6.0.1" />
    <PackageReference Include="Z.Dapper.Plus" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\Models\Matrix\" />
    <Folder Include="Core\Models\Nakl\" />
    <Folder Include="Core\Models\Prorabotki\" />
    <Folder Include="Core\Models\Raskr\" />
    <Folder Include="Core\Models\Vyaz\" />
    <Folder Include="Features\Sprav\Helpers\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
