<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>False</UseWPF>
    <StartupObject>SewingProduction.Core.Program</StartupObject>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <ApplicationIcon>Resources\favicon_io (1)\favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\Settings.cs" />
    <Compile Remove="Features\Settings.Designer.cs" />
    <Compile Remove="Features\TeamWork\Helpers\ANNGridViewHelper.cs" />
    <Compile Remove="Features\TeamWork\Helpers\AnnManager.cs" />
    <Compile Remove="Features\TeamWork\Helpers\ArtNormController.cs" />
    <Compile Remove="Features\TeamWork\Helpers\NormRaskManager.cs" />
    <Compile Remove="Features\TeamWork\Helpers\NormRaszManager.cs" />
    <Compile Remove="Features\TeamWork\Models\NormRasz1.cs" />
    <Compile Remove="Features\TeamWork\Models\NormRasz2.cs" />
    <Compile Remove="Report\PostReportFio.cs" />
    <Compile Remove="Report\PostReportFio.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Core\Class\CustomControls.resx" />
    <EmbeddedResource Remove="Report\PostReportFio.resx" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\favicon_io (1)\favicon.ico" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.1" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="DevExpress.Win.Design" Version="24.2.7" />
    <PackageReference Include="Microsoft.AspNet.Identity.Core" Version="2.2.4" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.5" />
    <PackageReference Include="Microsoft.ReportingServices.ReportViewerControl.WebForms" Version="150.1652.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NLog" Version="5.4.0" />
    <PackageReference Include="Z.Dapper.Plus" Version="7.5.12" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\Models\Matrix\" />
    <Folder Include="Core\Models\Nakl\" />
    <Folder Include="Core\Models\Prorabotki\" />
    <Folder Include="Core\Models\Raskr\" />
    <Folder Include="Core\Models\Vyaz\" />
    <Folder Include="Features\Sprav\Models\" />
    <Folder Include="Features\Sprav\Helpers\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
