<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>False</UseWPF>
    <StartupObject>SewingProduction.Core.Program</StartupObject>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <ApplicationIcon>Resources\AppIcons\favicon.ico</ApplicationIcon>
    <SignAssembly>False</SignAssembly>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>True</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\KnittingProduction\Forms\KnitterWorkSpace.patched.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="SplashImages\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>



  <ItemGroup>
    <Content Include="Help\Features\TeamWork\Forms\img\1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\10.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\11.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\12.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\13.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\14.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\7.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\8.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\img\9.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\TeamWork\Forms\TeamWork.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\AllRole.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Help\Features\UserDistribution\Forms\ActionHistory.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\AdminForm.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\AllUser.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Dictionary.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\ActionHistory.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AdminForm.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AllRole-SetForm.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AllRole-SetUser.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AllRole.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AllUser-AddUser.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AllUser-AddUser2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AllUser-SetRole.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\AllUser.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\Dictionary-add.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\Dictionary-add2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\Dictionary.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\RoleColumn.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\RoleColumnY.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\Settings.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\UserHierarchy.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Img\UserProfile.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\RoleColumn.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\Settings.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\UserHierarchy.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Features\UserDistribution\Forms\UserProfile.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\Help.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\AppIcons\favicon.ico" />
    <Content Include="Resources\cat-cat-rainbow.gif" />
    <EmbeddedResource Include="Resources\cat_square.gif">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Resources\loading_dude.gif" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="DevExpress.Win" Version="25.2.4" />
    <PackageReference Include="DevExpress.Win.BonusSkins" Version="25.2.4" />
    <PackageReference Include="DevExpress.Win.Design" Version="25.2.4" />
    <PackageReference Include="DevExpress.Win.Printing" Version="25.2.4" />
    <PackageReference Include="DevExpress.Win.Reporting" Version="25.2.4" />
    <PackageReference Include="DevExpress.Wpf.Core" Version="25.2.4" />
    <PackageReference Include="Microsoft.AspNet.Identity.Core" Version="2.2.4" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.2" />
    <PackageReference Include="Microsoft.ReportingServices.ReportViewerControl.WebForms" Version="150.1652.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.1.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Core\Class\CustomControls\CustomLayoutControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Report\TimeSheetReportZl.cs">
      <SubType>XtraReport</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\PublishProfiles\anyCPU.pubxml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\PublishProfiles\ClickOnceProfile.pubxml">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Properties\PublishProfiles\ver.x32.pubxml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Resources\free-icon-cursor-6825137.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\Models\Matrix\" />
    <Folder Include="Core\Models\Nakl\" />
    <Folder Include="Core\Models\Prorabotki\" />
    <Folder Include="Core\Models\Raskr\" />
    <Folder Include="Core\Models\Vyaz\" />
    <Folder Include="Features\SockProduction\Models\" />
    <Folder Include="Features\SockProduction\Services\" />
    <Folder Include="Features\Sprav\Helpers\" />
    <Folder Include="Features\Sprav\Service\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\gray_spinner.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <Content Include="Resources\loading_dude.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
