using DevExpress.XtraPrinting.Localization;
using System;

public class RussianPrintLocalizer : PreviewLocalizer
{
    public override string Language { get { return "Russian"; } }
    public override string GetLocalizedString(PreviewStringId id)
    {
        string retPrintLocal = String.Empty;
        switch (id)
        {
            case PreviewStringId.Button_Help: return "Справка";
            case PreviewStringId.TB_TTip_PageSetup: return "Параметры страницы";
            case PreviewStringId.MPForm_Lbl_Pages: return "Страницы";
            case PreviewStringId.SB_ZoomFactor: return "Масштаб:";
            case PreviewStringId.TB_TTip_ZoomIn: return "Увеличить";
            case PreviewStringId.TB_TTip_FirstPage: return "Первая страница";
            case PreviewStringId.TB_TTip_PreviousPage: return "Предыдущая страница";
            case PreviewStringId.TB_TTip_NextPage: return "Следующая страница";
            case PreviewStringId.Msg_EmptyDocument: return "Нет данных для вывода на печать.";
            case PreviewStringId.Msg_CreatingDocument: return "Создание документа...";
            case PreviewStringId.TB_TTip_MultiplePages: return "Несколько страниц";
            case PreviewStringId.Button_Apply: return "Применить";
            case PreviewStringId.TB_TTip_ZoomOut: return "Уменьшить";
            case PreviewStringId.TB_TTip_Zoom: return "Увеличить";
            case PreviewStringId.TB_TTip_PrintDirect: return "Печать";
            case PreviewStringId.TB_TTip_Magnifier: return "Увеличение";
            case PreviewStringId.TB_TTip_Print: return "Печать";
            case PreviewStringId.Button_Cancel: return "Отмена";
            case PreviewStringId.TB_TTip_Close: return "Закрыть просмотр";
            case PreviewStringId.TB_TTip_Backgr: return "Фон";
            case PreviewStringId.TB_TTip_EditPageHF: return "Колонтитулы";
            case PreviewStringId.Button_Ok: return "ОК";
            case PreviewStringId.SB_PageNone: return "(нет)";
            case PreviewStringId.TB_TTip_LastPage: return "Последняя страница";
            case PreviewStringId.Msg_UnavailableNetPrinter: return "Сетевой принтер недоступен.";
            case PreviewStringId.Msg_NeedPrinter: return "Принтер не установлен.";
            case PreviewStringId.Msg_WrongPrinter: return "Неверное имя принтера. Проверьте настройки принтера.";
            case PreviewStringId.Msg_WrongPrinting: return "Ошибка при печати документа";
            case PreviewStringId.Msg_WrongPageSettings: return "Выбранный принтер не поддерживает такой размер бумаги.\nПечатать?";
            case PreviewStringId.Msg_CustomDrawWarning: return "Предупреждение!";
            case PreviewStringId.PreviewForm_Caption: return "Просмотр";
            case PreviewStringId.TB_TTip_Customize: return "Настроить";
            case PreviewStringId.Margin_Inch: return "Дюйм";
            case PreviewStringId.Margin_Millimeter: return "мм";
            case PreviewStringId.Margin_TopMargin: return "Верхнее поле";
            case PreviewStringId.Margin_BottomMargin: return "Нижнее поле";
            case PreviewStringId.Margin_LeftMargin: return "Левое поле";
            case PreviewStringId.Margin_RightMargin: return "Правое поле";
            case PreviewStringId.ScrollingInfo_Page: return "Страница";
            case PreviewStringId.Msg_PageMarginsWarning: return "Одно или несколько полей лежат вне области печати. Продолжить?";
            case PreviewStringId.SB_PageInfo: return "Страница {0} из {1}";
            case PreviewStringId.TB_TTip_HandTool: return "Перемещать";
            case PreviewStringId.TB_TTip_Export: return "Экспорт";
            case PreviewStringId.TB_TTip_Send: return "Отправить по почте";
            case PreviewStringId.TB_TTip_Map: return "Оглавление";
            case PreviewStringId.TB_TTip_Search: return "Найти";
            case PreviewStringId.TB_TTip_Watermark: return "Подложка";
            case PreviewStringId.MenuItem_File: return "Файл";
            case PreviewStringId.MenuItem_View: return "Вид";
            case PreviewStringId.MenuItem_Background: return "Фон";
            case PreviewStringId.MenuItem_PageSetup: return "Параметры страницы...";
            case PreviewStringId.MenuItem_Print: return "Печать...";
            case PreviewStringId.MenuItem_PrintDirect: return "Печать на принтере по умолчанию";
            case PreviewStringId.MenuItem_Export: return "Экспорт";
            case PreviewStringId.MenuItem_Send: return "Отправить по почте";
            case PreviewStringId.MenuItem_Exit: return "Выход";
            case PreviewStringId.MenuItem_ViewToolbar: return "Панель инструментов";
            case PreviewStringId.MenuItem_ViewStatusbar: return "Строка состояния";
            case PreviewStringId.MenuItem_ViewContinuous: return "Скрыть пробелы";
            case PreviewStringId.MenuItem_ViewFacing: return "Показать пробелы";
            case PreviewStringId.MenuItem_BackgrColor: return "Заливка...";
            case PreviewStringId.MenuItem_Watermark: return "Подложка...";
            case PreviewStringId.MenuItem_PdfDocument: return "Документ Adobe Acrobat";
            case PreviewStringId.MenuItem_TxtDocument: return "Текстовый документ";
            case PreviewStringId.MenuItem_CsvDocument: return "CSV файл";
            case PreviewStringId.MenuItem_MhtDocument: return "Документ MHT";
            case PreviewStringId.MenuItem_XlsDocument: return "Документ Excel";
            case PreviewStringId.MenuItem_XlsxDocument: return "Документ Excel 2007";
            case PreviewStringId.MenuItem_RtfDocument: return "Форматированный текст";
            case PreviewStringId.MenuItem_HtmDocument: return "Документ HTML";
            case PreviewStringId.MenuItem_GraphicDocument: return "Картинка";
            case PreviewStringId.MenuItem_ZoomPageWidth: return "Ширина страницы";
            case PreviewStringId.MenuItem_ZoomTextWidth: return "Ширина текста";
            case PreviewStringId.MenuItem_ZoomWholePage: return "Страница целиком";
            case PreviewStringId.MenuItem_ZoomTwoPages: return "Две страницы";
            case PreviewStringId.MenuItem_PageLayout: return "Макет страницы";
            case PreviewStringId.SaveDlg_FilterPdf: return "Документ Adobe Acrobat";
            case PreviewStringId.SaveDlg_FilterTxt: return "Текстовый документ";
            case PreviewStringId.SaveDlg_FilterCsv: return "Документ CSV";
            case PreviewStringId.SaveDlg_FilterMht: return "Документ MHT";
            case PreviewStringId.SaveDlg_FilterXls: return "Документ Excel";
            case PreviewStringId.SaveDlg_FilterXlsx: return "Документ Excel (XLSX)";
            case PreviewStringId.SaveDlg_FilterRtf: return "Форматированный текст";
            case PreviewStringId.SaveDlg_FilterHtm: return "Документ HTML";
            case PreviewStringId.SaveDlg_FilterBmp: return "Картинка BMP";
            case PreviewStringId.SaveDlg_FilterGif: return "Картинка GIF";
            case PreviewStringId.SaveDlg_FilterJpeg: return "Картинка JPEG";
            case PreviewStringId.SaveDlg_FilterPng: return "Картинка PNG";
            case PreviewStringId.SaveDlg_FilterTiff: return "Картинка TIFF";
            case PreviewStringId.SaveDlg_FilterEmf: return "Картинка EMF";
            case PreviewStringId.SaveDlg_FilterWmf: return "Картинка WMF";
            case PreviewStringId.SaveDlg_FilterXps: return "Документ XPS";
            case PreviewStringId.SaveDlg_Title: return "Сохранение документа";
            case PreviewStringId.EMail_From: return "От";
            case PreviewStringId.Msg_IncorrectPageRange: return "Указан неверный диапазон печати.";
            case PreviewStringId.WMForm_ImageZoom: return "Масштабировать";
            case PreviewStringId.WMForm_Direction_Horizontal: return "По горизонтали";
            case PreviewStringId.WMForm_Direction_Vertical: return "По вертикали";
            case PreviewStringId.WMForm_Direction_BackwardDiagonal: return "По диагонали сверху вниз";
            case PreviewStringId.WMForm_Direction_ForwardDiagonal: return "По диагонали снизу вверх";
            case PreviewStringId.WMForm_VertAlign_Bottom: return "По нижнему краю";
            case PreviewStringId.WMForm_VertAlign_Middle: return "По середине";
            case PreviewStringId.WMForm_VertAlign_Top: return "По верхнему краю";
            case PreviewStringId.WMForm_HorzAlign_Left: return "По левому краю";
            case PreviewStringId.WMForm_HorzAlign_Center: return "По центру";
            case PreviewStringId.WMForm_HorzAlign_Right: return "По правому краю";
            case PreviewStringId.WMForm_PictureDlg_Title: return "Выбрать картинку";
            case PreviewStringId.WMForm_ImageStretch: return "Растянуть";
            case PreviewStringId.WMForm_ImageClip: return "Обрезать";
            case PreviewStringId.WMForm_Watermark_Asap: return "КАК МОЖНО СКОРЕЕ";
            case PreviewStringId.WMForm_Watermark_Confidential: return "КОНФИДЕНЦИАЛЬНО";
            case PreviewStringId.WMForm_Watermark_Copy: return "КОПИЯ";
            case PreviewStringId.WMForm_Watermark_DoNotCopy: return "НЕ КОПИРОВАТЬ";
            case PreviewStringId.WMForm_Watermark_Draft: return "ЧЕРНОВИК";
            case PreviewStringId.WMForm_Watermark_Evaluation: return "ОЦЕНКА";
            case PreviewStringId.WMForm_Watermark_Original: return "ОРИГИНАЛ";
            case PreviewStringId.WMForm_Watermark_Personal: return "ЛИЧНОЕ";
            case PreviewStringId.WMForm_Watermark_Sample: return "ОБРАЗЕЦ";
            case PreviewStringId.WMForm_Watermark_TopSecret: return "СЕКРЕТНО";
            case PreviewStringId.WMForm_Watermark_Urgent: return "НЕОТЛОЖНО";
            case PreviewStringId.Msg_FontInvalidNumber: return "Указано неверное число.";
            case PreviewStringId.Msg_NotSupportedFont: return "[Шрифт не поддерживается]";
            case PreviewStringId.Msg_NoDifferentFilesInStream: return "Документ не может быть экспортирован в поток в DifferentFiles режиме. Используйте SingleFile или SingleFilePageByPage режим.";
            case PreviewStringId.Msg_BigFileToCreate: return "Выходной файл слишком велик. Попробуйте уменьшить число страниц, или разбить его на несколько документов";
            case PreviewStringId.Msg_BigFileToCreateJPEG: return "Файл вывода слишком велик для создания JPEG файла. Пожалуйста, выберите другой формат изображения или другой режим экспорта.";
            case PreviewStringId.Msg_BigBitmapToCreate: return "Выходной файл слишком велик. Пожалуйста, попробуйте уменьшить разрешение изображения, или выберите другой режим экспорта";
            case PreviewStringId.Msg_XlsMoreThanMaxRows: return "Создаваемый XLS файл слишком велик для формата XLS, т.к. содержит более 65535 строк. Пожалуйста, попробуйте вместо этого экспорт в XLSX.";
            case PreviewStringId.Msg_XlsMoreThanMaxColumns: return "Создаваемый XLS файл слишком велик для формата XLS, т.к. содержит более 255 столбцов. Пожалуйста, попробуйте вместо этого экспорт в XLSX.";
            case PreviewStringId.Msg_XlsxMoreThanMaxRows: return "Создаваемый XLSX файл слишком велик для формата XLSX, т.к. содержит более 1 048 576 строк. Пожалуйста, попробуйте уменьшить число строк в отчете и экспортируйте в XLSX снова.";
            case PreviewStringId.Msg_XlsxMoreThanMaxColumns: return "Создаваемый XLSX файл слишком велик для формата XLSX, т.к. содержит более 16,384 столбцов. Пожалуйста, попробуйте уменьшить число столбцов в отчете и экспортируйте в XLSX снова.";
            case PreviewStringId.Msg_FileDosntHavePrnxExtention: return "Указанный файл не имеет расширения PRNX. Продолжить?";
            case PreviewStringId.Msg_FileDosntContainValidXml: return "Указанный файл не содержит корректных XML данных в PRNX формате. Загрузка остановлена.";
            case PreviewStringId.WMForm_ZOrderRgrItem_InFront: return "Поверх";
            case PreviewStringId.WMForm_ZOrderRgrItem_Behind: return "Снизу";
            case PreviewStringId.WMForm_PageRangeRgrItem_All: return "Все";
            case PreviewStringId.WMForm_PageRangeRgrItem_Pages: return "Страницы:";
            case PreviewStringId.PageInfo_PageNumber: return "[Страница #]";
            case PreviewStringId.PageInfo_PageNumberOfTotal: return "[Страница # из # страниц]";
            case PreviewStringId.PageInfo_PageDate: return "[Дата печати]";
            case PreviewStringId.PageInfo_PageTime: return "[Время печати]";
            case PreviewStringId.PageInfo_PageUserName: return "[Имя пользователя]";
            case PreviewStringId.BarText_Toolbar: return "Панель";
            case PreviewStringId.BarText_MainMenu: return "Главное меню";
            case PreviewStringId.BarText_StatusBar: return "Статус";
            case PreviewStringId.Msg_IncorrectZoomFactor: return "Число должно быть от {0} и до {1}.";
            case PreviewStringId.Msg_InvalidMeasurement: return "Это недопустимое измерение";
            case PreviewStringId.Msg_CannotAccessFile: return "Процесс не может получить доступ к файлу\"{0}\", так как он занят другим процессом";
            case PreviewStringId.Msg_FileReadOnly: return "Файл \"{0}\" предназначен только для чтения, попробуйте снова с другим именем файла.";
            case PreviewStringId.Msg_OpenFileQuestion: return "Вы хотите открыть этот файл?";
            case PreviewStringId.ScalePopup_AdjustTo: return "Установить в:";
            case PreviewStringId.ScalePopup_FitTo: return "Подогнать";
            case PreviewStringId.ScalePopup_PagesWide: return "ширина страницы";
            case PreviewStringId.ScalePopup_GroupText: return "Масштабирование";
            case PreviewStringId.ScalePopup_NormalSize: return "% от нормального размера";
            case PreviewStringId.TB_TTip_Scale: return "Масштаб";
            case PreviewStringId.ExportOption_RtfExportMode: return "Режим экспорта:";
            case PreviewStringId.ExportOption_RtfExportMode_SingleFile: return "Один файл без разбивки на страницы";
            case PreviewStringId.ExportOption_RtfExportMode_SingleFilePageByPage: return "Один файл с разбивкой на страницы";
            case PreviewStringId.ExportOption_RtfPageRange: return "Интервал страниц:";
            case PreviewStringId.ExportOption_RtfExportWatermarks: return "Экспорт водяных знаков";
            case PreviewStringId.ExportOption_PdfPageRange: return "Интервал страниц:";
            case PreviewStringId.ExportOption_PdfCompressed: return "Сжат";
            case PreviewStringId.ExportOption_PdfShowPrintDialogOnOpen: return "Показать диалог печати при открытии";
            case PreviewStringId.ExportOption_PdfNeverEmbeddedFonts: return "Эти шрифты не встроены:";
            case PreviewStringId.ExportOption_PdfImageQuality: return "Качество изображения:";
            case PreviewStringId.ExportOption_PdfImageQuality_Lowest: return "Самое низкое";
            case PreviewStringId.ExportOption_PdfImageQuality_Low: return "Низкое";
            case PreviewStringId.ExportOption_PdfImageQuality_Medium: return "Среднее";
            case PreviewStringId.ExportOption_PdfImageQuality_High: return "Высокое";
            case PreviewStringId.ExportOption_PdfImageQuality_Highest: return "Самое лучшее";
            case PreviewStringId.ExportOption_PdfDocumentAuthor: return "Автор:";
            case PreviewStringId.ExportOption_PdfDocumentApplication: return "Приложение:";
            case PreviewStringId.ExportOption_PdfDocumentTitle: return "Название:";
            case PreviewStringId.ExportOption_PdfDocumentSubject: return "Предмет:";
            case PreviewStringId.ExportOption_PdfDocumentKeywords: return "Ключевые слова:";
            case PreviewStringId.ExportOption_HtmlExportMode: return "Режим экспорта:";
            case PreviewStringId.ExportOption_HtmlExportMode_SingleFile: return "Один файл без разбивки на страницы";
            case PreviewStringId.ExportOption_HtmlExportMode_SingleFilePageByPage: return "Один файл с разбивкой на страницы";
            case PreviewStringId.ExportOption_HtmlExportMode_DifferentFiles: return "Каждая страница в отдельном файле";
            case PreviewStringId.ExportOption_HtmlCharacterSet: return "Набор символов:";
            case PreviewStringId.ExportOption_HtmlTitle: return "Название:";
            case PreviewStringId.ExportOption_HtmlRemoveSecondarySymbols: return "Убрать возврат коретки";
            case PreviewStringId.ExportOption_HtmlPageRange: return "Интервал страниц:";
            case PreviewStringId.ExportOption_HtmlPageBorderWidth: return "Ширина границы страницы:";
            case PreviewStringId.ExportOption_HtmlPageBorderColor: return "Цвет границы страницы:";
            case PreviewStringId.ExportOption_TextSeparator: return "Разделитель текста:";
            case PreviewStringId.ExportOption_TextEncoding: return "Кодировка:";
            case PreviewStringId.ExportOption_XlsShowGridLines: return "Показать линии сетки";
            case PreviewStringId.ExportOption_XlsUseNativeFormat: return "Экспортировать значения используя их формат";
            case PreviewStringId.ExportOption_XlsExportHyperlinks: return "Экспорт гиперссылок";
            case PreviewStringId.ExportOption_ImageExportMode: return "Режим экспорта:";
            case PreviewStringId.ExportOption_ImageExportMode_SingleFile: return "Один файл без разбивки на страницы";
            case PreviewStringId.ExportOption_ImageExportMode_SingleFilePageByPage: return "Один файл с разбивкой на страницы";
            case PreviewStringId.ExportOption_ImageExportMode_DifferentFiles: return "Каждая страница в отдельном файле";
            case PreviewStringId.ExportOption_ImagePageRange: return "Интервал страниц:";
            case PreviewStringId.ExportOption_ImagePageBorderWidth: return "Ширина границы страницы:";
            case PreviewStringId.ExportOption_ImagePageBorderColor: return "Цвет границы страницы:";
            case PreviewStringId.ExportOption_ImageResolution: return "Разрешающая способность (dpi):";
            case PreviewStringId.ExportOption_ImageFormat: return "Формат изображения:";
            case PreviewStringId.ExportOption_XpsPageRange: return "Диапазон страниц:";
            case PreviewStringId.ExportOption_XpsCompression: return "Опции сжатия:";
            case PreviewStringId.ExportOption_XpsCompression_NotCompressed: return "Не сжатый";
            case PreviewStringId.ExportOption_XpsCompression_Normal: return "Нормальный";
            case PreviewStringId.ExportOption_XpsCompression_Maximum: return "Максимально";
            case PreviewStringId.ExportOption_XpsCompression_Fast: return "Быстро";
            case PreviewStringId.ExportOption_XpsCompression_SuperFast: return "Супер быстро";
            case PreviewStringId.ExportOption_XpsDocumentCreator: return "Разработчик:";
            case PreviewStringId.ExportOption_XpsDocumentCategory: return "Категория:";
            case PreviewStringId.ExportOption_XpsDocumentTitle: return "Название:";
            case PreviewStringId.ExportOption_XpsDocumentSubject: return "Предмет:";
            case PreviewStringId.ExportOption_XpsDocumentKeywords: return "Ключевые слова:";
            case PreviewStringId.ExportOption_XpsDocumentVersion: return "Версия:";
            case PreviewStringId.ExportOption_XpsDocumentDescription: return "Описание:";
            case PreviewStringId.FolderBrowseDlg_ExportDirectory: return "Выберите папку для сохранения документов для экспорта:";
            case PreviewStringId.ExportOptionsForm_CaptionPdf: return "Опции экспорта PDF";
            case PreviewStringId.ExportOptionsForm_CaptionXls: return "Опции экспорта XLS";
            case PreviewStringId.ExportOptionsForm_CaptionXlsx: return "Опции экспорта XLSX";
            case PreviewStringId.ExportOptionsForm_CaptionTxt: return "Опции экспорта текста";
            case PreviewStringId.ExportOptionsForm_CaptionCsv: return "Опции экспорта CSV";
            case PreviewStringId.ExportOptionsForm_CaptionImage: return "Опции экспорта изображения";
            case PreviewStringId.ExportOptionsForm_CaptionHtml: return "Опции экспорта HTML";
            case PreviewStringId.ExportOptionsForm_CaptionMht: return "Опции экспорта MHT";
            case PreviewStringId.ExportOptionsForm_CaptionRtf: return "Опции экспорта RTF";
            case PreviewStringId.ExportOptionsForm_CaptionXps: return "Опции экспорта XPS";
            case PreviewStringId.RibbonPreview_GalleryItem_PageMargins_Description: return "Верх:{0} Низ:{1} Лево: {2} Право: {3}";
            case PreviewStringId.RibbonPreview_GalleryItem_PaperSize_Description: return "{0} x {1}";
            case PreviewStringId.RibbonPreview_PageGroup_Print: return "Печать";
            case PreviewStringId.RibbonPreview_PageGroup_PageSetup: return "Настройки страницы";
            case PreviewStringId.RibbonPreview_PageGroup_Navigation: return "Управление";
            case PreviewStringId.RibbonPreview_PageGroup_Zoom: return "Масштаб";
            case PreviewStringId.RibbonPreview_PageGroup_Background: return "Фон страницы";
            case PreviewStringId.RibbonPreview_PageGroup_Export: return "Экспорт";
            case PreviewStringId.RibbonPreview_DocumentMap_Caption: return "Закладки";
            case PreviewStringId.RibbonPreview_Find_Caption: return "Найти";
            case PreviewStringId.RibbonPreview_Pointer_Caption: return "Указатель";
            case PreviewStringId.RibbonPreview_HandTool_Caption: return "Ручная настройка";
            case PreviewStringId.RibbonPreview_Customize_Caption: return "Опции";
            case PreviewStringId.RibbonPreview_Print_Caption: return "Печать";
            case PreviewStringId.RibbonPreview_PrintDirect_Caption: return "Быстрая печать";
            case PreviewStringId.RibbonPreview_PageSetup_Caption: return "Настройка полей...";
            case PreviewStringId.RibbonPreview_EditPageHF_Caption: return "Колонтитулы";
            case PreviewStringId.RibbonPreview_Magnifier_Caption: return "Увеличитель";
            case PreviewStringId.RibbonPreview_ZoomOut_Caption: return "Уменьшить";
            case PreviewStringId.RibbonPreview_ZoomIn_Caption: return "Увеличить";
            case PreviewStringId.RibbonPreview_ShowFirstPage_Caption: return "Первая страница";
            case PreviewStringId.RibbonPreview_ShowPrevPage_Caption: return "Предыдущая страница";
            case PreviewStringId.RibbonPreview_ShowNextPage_Caption: return "Следующая страница";
            case PreviewStringId.RibbonPreview_ShowLastPage_Caption: return "Последняя страница";
            case PreviewStringId.RibbonPreview_MultiplePages_Caption: return "Много страниц";
            case PreviewStringId.RibbonPreview_FillBackground_Caption: return "Цвет страницы";
            case PreviewStringId.RibbonPreview_Watermark_Caption: return "Водяной знак";
            case PreviewStringId.RibbonPreview_ExportFile_Caption: return "Экспортировать в";
            case PreviewStringId.RibbonPreview_SendFile_Caption: return "E-Mail как";
            case PreviewStringId.RibbonPreview_ClosePreview_Caption: return "Закрыть предпросмотр печати";
            case PreviewStringId.RibbonPreview_Scale_Caption: return "Масштаб";
            case PreviewStringId.RibbonPreview_PageOrientation_Caption: return "Направление";
            case PreviewStringId.RibbonPreview_PaperSize_Caption: return "Размер";
            case PreviewStringId.RibbonPreview_PageMargins_Caption: return "Поля";
            case PreviewStringId.RibbonPreview_Zoom_Caption: return "Масштаб";
            case PreviewStringId.RibbonPreview_DocumentMap_STipTitle: return "Схема документа";
            case PreviewStringId.RibbonPreview_Find_STipTitle: return "Найти";
            case PreviewStringId.RibbonPreview_Pointer_STipTitle: return "Указатель мыши";
            case PreviewStringId.RibbonPreview_HandTool_STipTitle: return "Ручная настройка";
            case PreviewStringId.RibbonPreview_Customize_STipTitle: return "Опции";
            case PreviewStringId.RibbonPreview_Print_STipTitle: return "Печать (Ctrl+P)";
            case PreviewStringId.RibbonPreview_PrintDirect_STipTitle: return "Быстрая печать";
            case PreviewStringId.RibbonPreview_PageSetup_STipTitle: return "Настройки страницы";
            case PreviewStringId.RibbonPreview_EditPageHF_STipTitle: return "Заголовок и нижний колонтинтул";
            case PreviewStringId.RibbonPreview_Magnifier_STipTitle: return "Увеличитель";
            case PreviewStringId.RibbonPreview_ZoomOut_STipTitle: return "Уменьшить";
            case PreviewStringId.RibbonPreview_ZoomIn_STipTitle: return "Увеличить";
            case PreviewStringId.RibbonPreview_ShowFirstPage_STipTitle: return "Первая страница (Ctrl+Home)";
            case PreviewStringId.RibbonPreview_ShowPrevPage_STipTitle: return "Предыдущая страница (PageUp)";
            case PreviewStringId.RibbonPreview_ShowNextPage_STipTitle: return "Следующая страница (PageDown)";
            case PreviewStringId.RibbonPreview_ShowLastPage_STipTitle: return "Последняя страница (Ctrl+End)";
            case PreviewStringId.RibbonPreview_MultiplePages_STipTitle: return "Много страниц";
            case PreviewStringId.RibbonPreview_FillBackground_STipTitle: return "Цвет фона";
            case PreviewStringId.RibbonPreview_Watermark_STipTitle: return "Водяной знак";
            case PreviewStringId.RibbonPreview_ExportFile_STipTitle: return "Экспорт в...";
            case PreviewStringId.RibbonPreview_SendFile_STipTitle: return "E-Mail как...";
            case PreviewStringId.RibbonPreview_ClosePreview_STipTitle: return "Закрыть предпросмотр печати";
            case PreviewStringId.RibbonPreview_Scale_STipTitle: return "Масштаб";
            case PreviewStringId.RibbonPreview_PageOrientation_STipTitle: return "Положение страницы";
            case PreviewStringId.RibbonPreview_PaperSize_STipTitle: return "Размер страницы";
            case PreviewStringId.RibbonPreview_PageMargins_STipTitle: return "Поля страницы";
            case PreviewStringId.RibbonPreview_Zoom_STipTitle: return "Масштаб";
            case PreviewStringId.RibbonPreview_PageGroup_PageSetup_STipTitle: return "Настройки страницы";
            case PreviewStringId.RibbonPreview_DocumentMap_STipContent: return "Открыть схему документа, которая позволит быстрее разобраться в структуре документа.";
            case PreviewStringId.RibbonPreview_Find_STipContent: return "Запуск диалогового окна поиска для нахождения текста в документе.";
            case PreviewStringId.RibbonPreview_Pointer_STipContent: return "Отобразить указатель мыши.";
            case PreviewStringId.RibbonPreview_HandTool_STipContent: return "Разрешить ручную прокрутку для просмотра страниц.";
            case PreviewStringId.RibbonPreview_Customize_STipContent: return "Открытие диалогового окна для изменения настроек печати.";
            case PreviewStringId.RibbonPreview_Print_STipContent: return "Выберите принтер, количество копий и другие необходимые настройки перед печатью.";
            case PreviewStringId.RibbonPreview_PrintDirect_STipContent: return "Отправить документ на распечатку без сделанных изменений.";
            case PreviewStringId.RibbonPreview_PageSetup_STipContent: return "Вызов диалога настроек страницы.";
            case PreviewStringId.RibbonPreview_EditPageHF_STipContent: return "Редактировать заголовок и нижний колонтинтул документа.";
            case PreviewStringId.RibbonPreview_Magnifier_STipContent: return "Запуск увеличителя. Нажатие на масштаб приводит к тому, что документ становится увеличенным, повторное нажатие приводит его к нормальному состоянию.";
            case PreviewStringId.RibbonPreview_ZoomOut_STipContent: return "Уменьшить для отображения большего количества страниц.";
            case PreviewStringId.RibbonPreview_ZoomIn_STipContent: return "Увеличить для лучшего просмотра документа.";
            case PreviewStringId.RibbonPreview_ShowFirstPage_STipContent: return "Переход на первую страницу документа.";
            case PreviewStringId.RibbonPreview_ShowPrevPage_STipContent: return "Переход на предыдущую страницу документа.";
            case PreviewStringId.RibbonPreview_ShowNextPage_STipContent: return "Переход на следующую страницу документа.";
            case PreviewStringId.RibbonPreview_ShowLastPage_STipContent: return "Переход на последнюю страницу документа.";
            case PreviewStringId.RibbonPreview_MultiplePages_STipContent: return "Выберите положение страницы для предпросмотра.";
            case PreviewStringId.RibbonPreview_FillBackground_STipContent: return "Выберите цвет для фона документа.";
            case PreviewStringId.RibbonPreview_Watermark_STipContent: return "Вставьте ореол текста или изображения за содержимым страницы.Это позволит указать на важность документа.";
            case PreviewStringId.RibbonPreview_ExportFile_STipContent: return "Экспортировать текущий документ в один из доступных форматов, и сохранить его на диске.";
            case PreviewStringId.RibbonPreview_SendFile_STipContent: return "Экспортировать текущий документ в один из доступных форматов, и добавить на e-mail.";
            case PreviewStringId.RibbonPreview_ClosePreview_STipContent: return "Закрыть предпросмотр печати документа.";
            case PreviewStringId.RibbonPreview_Scale_STipContent: return "Растяжение или сжатие выводимого на печать.";
            case PreviewStringId.RibbonPreview_PageOrientation_STipContent: return "Переключение между вертикальным и горизонтальным расположением страницы.";
            case PreviewStringId.RibbonPreview_PaperSize_STipContent: return "Выберите размер бумаги для документа.";
            case PreviewStringId.RibbonPreview_PageMargins_STipContent: return "Выбор размеров поля для документа. Для применения настроек для поля, выберите Настройки полей.";
            case PreviewStringId.RibbonPreview_Zoom_STipContent: return "Выберите уровень масштабирования для предпросмотра документа.";
            case PreviewStringId.RibbonPreview_PageGroup_PageSetup_STipContent: return "Вызов диалога настроек страницы.";
            case PreviewStringId.RibbonPreview_ExportPdf_Caption: return "PDF файл";
            case PreviewStringId.RibbonPreview_ExportHtm_Caption: return "HTML файл";
            case PreviewStringId.RibbonPreview_ExportMht_Caption: return "MHT файл";
            case PreviewStringId.RibbonPreview_ExportTxt_Caption: return "Текстовый файл";
            case PreviewStringId.RibbonPreview_ExportCsv_Caption: return "CSV файл";
            case PreviewStringId.RibbonPreview_ExportXls_Caption: return "Excel файл";
            case PreviewStringId.RibbonPreview_ExportXlsx_Caption: return "Excel файл (.XLSX)";
            case PreviewStringId.RibbonPreview_ExportRtf_Caption: return "RTF файл";
            case PreviewStringId.RibbonPreview_ExportGraphic_Caption: return "Файл изображения";
            case PreviewStringId.RibbonPreview_ExportXps_Caption: return "XPS Файл";
            case PreviewStringId.RibbonPreview_SendPdf_Caption: return "PDF файл";
            case PreviewStringId.RibbonPreview_SendTxt_Caption: return "Текстовый файл";
            case PreviewStringId.RibbonPreview_SendCsv_Caption: return "CSV файл";
            case PreviewStringId.RibbonPreview_SendMht_Caption: return "MHT файл";
            case PreviewStringId.RibbonPreview_SendXls_Caption: return "Excel файл";
            case PreviewStringId.RibbonPreview_SendXlsx_Caption: return "Excel файл (XLSX)";
            case PreviewStringId.RibbonPreview_SendRtf_Caption: return "RTF файл";
            case PreviewStringId.RibbonPreview_SendGraphic_Caption: return "Файл изображения";
            case PreviewStringId.RibbonPreview_SendXps_Caption: return "Файл XPS ";
            case PreviewStringId.RibbonPreview_GalleryItem_PageOrientationPortrait_Caption: return "Вертикально";
            case PreviewStringId.RibbonPreview_GalleryItem_PageOrientationLandscape_Caption: return "Горизонтально";
            case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNormal_Caption: return "Нормальный";
            case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNarrow_Caption: return "Узкий";
            case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsModerate_Caption: return "Умеренный";
            case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsWide_Caption: return "Широкий";
            case PreviewStringId.RibbonPreview_ExportPdf_Description: return "Формат Adobe Portable Document";
            case PreviewStringId.RibbonPreview_ExportHtm_Description: return "Web страница";
            case PreviewStringId.RibbonPreview_ExportTxt_Description: return "Открытый текст";
            case PreviewStringId.RibbonPreview_ExportCsv_Description: return "Текстовые значения через запятую";
            case PreviewStringId.RibbonPreview_ExportMht_Description: return "Веб-страница в одном файле";
            case PreviewStringId.RibbonPreview_ExportXls_Description: return "Книга Microsoft Excel";
            case PreviewStringId.RibbonPreview_ExportXlsx_Description: return "Книга Microsoft Excel 2007";
            case PreviewStringId.RibbonPreview_ExportRtf_Description: return "Форматированный текст";
            case PreviewStringId.RibbonPreview_ExportGraphic_Description: return "BMP, GIF, JPEG, PNG, TIFF, EMF, WMF";
            case PreviewStringId.RibbonPreview_ExportXps_Description: return "XPS";
            case PreviewStringId.RibbonPreview_SendPdf_Description: return "Формат Adobe Portable Document";
            case PreviewStringId.RibbonPreview_SendTxt_Description: return "Открытый текст";
            case PreviewStringId.RibbonPreview_SendCsv_Description: return "Текстовые значения через запятую";
            case PreviewStringId.RibbonPreview_SendMht_Description: return "Веб-страница в одном файле";
            case PreviewStringId.RibbonPreview_SendXls_Description: return "Книга Microsoft Excel";
            case PreviewStringId.RibbonPreview_SendXlsx_Description: return "Книга Microsoft Excel 2007";
            case PreviewStringId.RibbonPreview_SendRtf_Description: return "Rich Text Format";
            case PreviewStringId.RibbonPreview_SendGraphic_Description: return "BMP, GIF, JPEG, PNG, TIFF, EMF, WMF";
            case PreviewStringId.RibbonPreview_SendXps_Description: return "XPS";
            case PreviewStringId.RibbonPreview_GalleryItem_PageOrientationPortrait_Description: return " Описание портретной ориентации";
            case PreviewStringId.RibbonPreview_GalleryItem_PageOrientationLandscape_Description: return " Описание альбомной ориентации";
            case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNormal_Description: return "Нормальный";
            case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsNarrow_Description: return "Узкий";
            case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsModerate_Description: return "Умеренный";
            case PreviewStringId.RibbonPreview_GalleryItem_PageMarginsWide_Description: return "Широкий";
            case PreviewStringId.Msg_OpenFileQuestionCaption: return "Экспорт";
            case PreviewStringId.RibbonPreview_ExportPdf_STipTitle: return "Экспорт в PDF";
            case PreviewStringId.RibbonPreview_ExportHtm_STipTitle: return "Экспорт в HTML";
            case PreviewStringId.RibbonPreview_ExportTxt_STipTitle: return "Экспорт в Text";
            case PreviewStringId.RibbonPreview_ExportCsv_STipTitle: return "Экспорт в CSV";
            case PreviewStringId.RibbonPreview_ExportMht_STipTitle: return "Экспорт в MHT";
            case PreviewStringId.RibbonPreview_ExportXls_STipTitle: return "Экспорт в XLS";
            case PreviewStringId.RibbonPreview_ExportXlsx_STipTitle: return "Экспорт в XLSX";
            case PreviewStringId.RibbonPreview_ExportRtf_STipTitle: return "Экспорт в RTF";
            case PreviewStringId.RibbonPreview_ExportGraphic_STipTitle: return "Экспорт в Image";
            case PreviewStringId.RibbonPreview_SendPdf_STipTitle: return "E-Mail как PDF";
            case PreviewStringId.RibbonPreview_SendTxt_STipTitle: return "E-Mail как текст";
            case PreviewStringId.RibbonPreview_SendCsv_STipTitle: return "E-Mail как CSV";
            case PreviewStringId.RibbonPreview_SendMht_STipTitle: return "E-Mail как MHT";
            case PreviewStringId.RibbonPreview_SendXls_STipTitle: return "E-Mail как XLS";
            case PreviewStringId.RibbonPreview_SendXlsx_STipTitle: return "E-Mail как XLSX";
            case PreviewStringId.RibbonPreview_SendRtf_STipTitle: return "E-Mail как RTF";
            case PreviewStringId.RibbonPreview_SendGraphic_STipTitle: return "E-Mail как изображение";
            case PreviewStringId.RibbonPreview_ExportPdf_STipContent: return "Экспорт документа в PDF  и сохранение его на диске.";
            case PreviewStringId.RibbonPreview_ExportHtm_STipContent: return "Экспорт документа в HTML  и сохранение его на диске.";
            case PreviewStringId.RibbonPreview_ExportTxt_STipContent: return "Экспорт документа в Text  и сохранение его на диске.";
            case PreviewStringId.RibbonPreview_ExportCsv_STipContent: return "Экспорт документа в CSV и сохранение его на диске.";
            case PreviewStringId.RibbonPreview_ExportMht_STipContent: return "Экспорт документа в MHT и сохранение его на диске.";
            case PreviewStringId.RibbonPreview_ExportXls_STipContent: return "Экспорт документа в XLS  и сохранение его на диске.";
            case PreviewStringId.RibbonPreview_ExportXlsx_STipContent: return "Экспорт документа в XLSX  и сохранение его на диске.";
            case PreviewStringId.RibbonPreview_ExportRtf_STipContent: return "Экспорт документа в RTF  и сохранение его на диске.";
            case PreviewStringId.RibbonPreview_ExportGraphic_STipContent: return "Экспорт документа в Image  и сохранение его на диске.";
            case PreviewStringId.RibbonPreview_SendPdf_STipContent: return "Экспорт документа в PDF и добавление его в e-mail.";
            case PreviewStringId.RibbonPreview_SendTxt_STipContent: return "Экспорт документа в Text и добавление его в e-mail.";
            case PreviewStringId.RibbonPreview_SendCsv_STipContent: return "Экспорт документа в CSV и добавление его на e-mail.";
            case PreviewStringId.RibbonPreview_SendMht_STipContent: return "Экспорт документа в MHT и добавление его в e-mail.";
            case PreviewStringId.RibbonPreview_SendXls_STipContent: return "Экспорт документа в XLS и добавление его в e-mail.";
            case PreviewStringId.RibbonPreview_SendXlsx_STipContent: return "Экспорт документа в XLSX и добавление его в e-mail";
            case PreviewStringId.RibbonPreview_SendRtf_STipContent: return "Экспорт документа в RTF и добавление его в e-mail.";
            case PreviewStringId.RibbonPreview_SendGraphic_STipContent: return "Экспорт документа в Image и добавление его в e-mail.";
            case PreviewStringId.RibbonPreview_PageText: return "Предпросмотр печати";
            case PreviewStringId.RibbonPreview_ZoomExact_Caption: return "Точный:";
            case PreviewStringId.Msg_CantFitBarcodeToControlBounds: return "Границы управления являются слишком маленькими для штрихового кода";
            case PreviewStringId.Msg_InvalidBarcodeText: return "В тексте есть запрещенные символы";
            case PreviewStringId.Msg_InvalidBarcodeTextFormat: return "Недопустимый текстовый формат";
            case PreviewStringId.Msg_InvalidBarcodeData: return "Двоичные данные не могут быть длиннее 1033 байт.";
            case PreviewStringId.Msg_SearchDialogFinishedSearching: return "Закончен поиск по документу";
            case PreviewStringId.Msg_SearchDialogTotalFound: return "Найденное общее количество: ";
            case PreviewStringId.Msg_SearchDialogReady: return "Готов";
            case PreviewStringId.ExportOption_TextSeparator_TabAlias: return "ТАБУЛИРОВАТЬ";
            case PreviewStringId.ExportOption_TextQuoteStringsWithSeparators: return "Цитата строки с разделителями";
            case PreviewStringId.ExportOption_TextExportMode: return "Режим экспорта текста:";
            case PreviewStringId.ExportOption_TextExportMode_Value: return "Значение";
            case PreviewStringId.ExportOption_TextExportMode_Text: return "Текст";
            case PreviewStringId.RibbonPreview_PageGroup_Document: return "Документ";
            case PreviewStringId.RibbonPreview_Save_Caption: return "Сохранить";
            case PreviewStringId.RibbonPreview_Open_Caption: return "Открыть";
            case PreviewStringId.RibbonPreview_Save_STipTitle: return "Сохранить (Ctrl + S)";
            case PreviewStringId.RibbonPreview_Open_STipTitle: return "Открыть (Ctrl + O)";
            case PreviewStringId.RibbonPreview_Save_STipContent: return "Сохранить документ.";
            case PreviewStringId.RibbonPreview_Open_STipContent: return "Открыть документ.";
            case PreviewStringId.SaveDlg_FilterNativeFormat: return "Родной формат";
            case PreviewStringId.ExportOption_NativeFormatCompressed: return "Сжатый";
            case PreviewStringId.ExportOptionsForm_CaptionNativeOptions: return "Опции родного формата";
            case PreviewStringId.OpenFileDialog_Filter: return "Файлы документа для предпросмотра (*{0})|*{0}|Все файлы (*.*)|*.*";
            case PreviewStringId.OpenFileDialog_Title: return "Открыть";
            case PreviewStringId.TB_TTip_Open: return "Открыть документ";
            case PreviewStringId.TB_TTip_Save: return "Сохранить документ";
            case PreviewStringId.ExportOption_XlsSheetName: return "Имя листа:";
            case PreviewStringId.TB_TTip_Parameters: return "Параметры";
            case PreviewStringId.RibbonPreview_Parameters_Caption: return "Параметры";
            case PreviewStringId.RibbonPreview_Parameters_STipTitle: return "Параметры";
            case PreviewStringId.RibbonPreview_Parameters_STipContent: return "Открыть панель параметров для задания значений в параметров отчета";
            case PreviewStringId.SB_PageOfPages: return "Страница {0} из {1}";
            case PreviewStringId.Msg_Caption: return "Печать";
            case PreviewStringId.Shapes_Rectangle: return "Прямоугольник";
            case PreviewStringId.Shapes_Ellipse: return "Эллипс";
            case PreviewStringId.Shapes_Arrow: return "Стрелка";
            case PreviewStringId.Shapes_TopArrow: return "Стрелка вверх";
            case PreviewStringId.Shapes_BottomArrow: return "Стрелка вниз";
            case PreviewStringId.Shapes_LeftArrow: return "Стрелка влево";
            case PreviewStringId.Shapes_RightArrow: return "Стрелка вправо";
            case PreviewStringId.Shapes_Polygon: return "Многоугольник";
            case PreviewStringId.Shapes_Triangle: return "Треугольник";
            case PreviewStringId.Shapes_Square: return "Квадрат";
            case PreviewStringId.Shapes_Pentagon: return "Пятиугольник";
            case PreviewStringId.Shapes_Hexagon: return "Шестиугольник";
            case PreviewStringId.Shapes_Octagon: return "Восьмиугольник";
            case PreviewStringId.Shapes_Star: return "Звезда";
            case PreviewStringId.Shapes_ThreePointStar: return "3-лучевая звезда";
            case PreviewStringId.Shapes_FourPointStar: return "4-лучевая звезда";
            case PreviewStringId.Shapes_FivePointStar: return "5-лучевая звезда";
            case PreviewStringId.Shapes_SixPointStar: return "6-лучевая звезда";
            case PreviewStringId.Shapes_EightPointStar: return "8-лучевая звезда";
            case PreviewStringId.Shapes_Line: return "Линия";
            case PreviewStringId.Shapes_SlantLine: return "Наклонная линия";
            case PreviewStringId.Shapes_BackslantLine: return "Линия с обратным наклоном";
            case PreviewStringId.Shapes_HorizontalLine: return "Горизонтальная линия";
            case PreviewStringId.Shapes_VerticalLine: return "Вертикальная линия";
            case PreviewStringId.Shapes_Cross: return "Крест";
            case PreviewStringId.Shapes_Brace: return "Фигурная скобка";
            case PreviewStringId.Shapes_Bracket: return "Скобка";
            case PreviewStringId.SB_TTip_Stop: return "Стоп";
            case PreviewStringId.ExportOption_XlsExportMode: return "Режим экспорта:";
            case PreviewStringId.ExportOption_XlsExportMode_SingleFile: return "Один файл без разбивки на страницы";
            case PreviewStringId.ExportOption_XlsExportMode_DifferentFiles: return "Каждая страница в отдельном файле";
            case PreviewStringId.ExportOption_XlsPageRange: return "Диапазон страниц:";
            case PreviewStringId.ExportOption_XlsxExportMode: return "Режим экспорта:";
            case PreviewStringId.ExportOption_XlsxExportMode_SingleFile: return "Один файл без разбивки на страницы";
            case PreviewStringId.ExportOption_XlsxExportMode_SingleFilePageByPage: return "Один файл с разбивкой на страницы";
            case PreviewStringId.ExportOption_XlsxExportMode_DifferentFiles: return "Каждая страница в отдельном файле";
            case PreviewStringId.ExportOption_XlsxPageRange: return "Диапазон страниц:";
            case PreviewStringId.Msg_GoToNonExistentPage: return "Эта страница не пронумерована {0} в этом документе.";
            //DevExpress.XtraPrinting.PdfPermissionsOptions.ChangingPermissions : return "Изменение прав доступа";
            case PreviewStringId.ExportOption_PdfPrintingPermissions_None: return "Нет";
            case PreviewStringId.ExportOption_PdfPrintingPermissions_LowResolution: return "Низкое разрешение (150 dpi)";
            case PreviewStringId.ExportOption_PdfPrintingPermissions_HighResolution: return "Высокое разрешение";
            case PreviewStringId.ExportOption_PdfChangingPermissions_None: return "Нет";
            case PreviewStringId.ExportOption_PdfChangingPermissions_InsertingDeletingRotating: return "Вставка, удаление и вращение страниц";
            case PreviewStringId.ExportOption_PdfChangingPermissions_FillingSigning: return "Заполнение в полях формы и подписывая существующие поля сигнатуры";
            case PreviewStringId.ExportOption_PdfChangingPermissions_CommentingFillingSigning: return "Комментарий, заполняя в полях формы, и подписывая существующие поля сигнатуры...";
            case PreviewStringId.ExportOption_PdfChangingPermissions_AnyExceptExtractingPages: return "Любой кроме выделения страниц";
            case PreviewStringId.ExportOption_ConfirmOpenPasswordForm_Caption: return "Подтверждать пароль открытия документа";
            case PreviewStringId.ExportOption_ConfirmOpenPasswordForm_Note: return "Пожалуйста подтвердите пароль. Обратите внимание на пароль. Это необходимо для открытия документа.";
            case PreviewStringId.ExportOption_ConfirmOpenPasswordForm_Name: return "Пароль для открытия документа:";
            case PreviewStringId.ExportOption_ConfirmPermissionsPasswordForm_Caption: return "Подтверждать пароль прав доступа";
            case PreviewStringId.ExportOption_ConfirmPermissionsPasswordForm_Note: return "Пожалуйста подтвердите пароль прав доступа. Обратите внимание на пароль. Вы будете нуждаться в этом, чтобы изменить эти параметры настройки в будущем.";
            case PreviewStringId.ExportOption_ConfirmPermissionsPasswordForm_Name: return "Пароль прав доступа:";
            case PreviewStringId.ExportOption_ConfirmationDoesNotMatchForm_Msg: return "Пароль не соответствует. Пожалуйста введите пароль снова.";
            case PreviewStringId.ExportOption_PdfPasswordSecurityOptions: return "Защита паролем:";
            case PreviewStringId.ParametersRequest_Reset: return "Перегрузить";
            case PreviewStringId.ParametersRequest_Caption: return "Параметры";
            case PreviewStringId.ParametersRequest_Submit: return "Подтвердить";
            case PreviewStringId.ExportOption_HtmlEmbedImagesInHTML: return "Встраивать изображения в HTML";
            case PreviewStringId.ExportOption_PdfConvertImagesToJpeg: return "Конвертировать изображения в Jpeg";
            case PreviewStringId.ExportOption_PdfPasswordSecurityOptions_None: return "(нет)";
            case PreviewStringId.ExportOption_PdfPasswordSecurityOptions_Permissions: return "Разрешения";
            case PreviewStringId.ExportOption_PdfPasswordSecurityOptions_DocumentOpenPassword: return "Пароль на открытие документа";
            case PreviewStringId.Msg_PathTooLong: return "Путь слишком длинный. Попробуйте его сократить.";
            //case  DevExpress.XtraPrinting.PdfPasswordSecurityOptions.PermissionsPassword: return "Пароль разрешений"; // не смог разобраться как локализировать элементы диалоговых форм
            //case DevExpress.XtraPrinting.PdfPasswordSecurityOptions.PermissionsPassword : return "Пароль разрешений";
            //case DevExpress.XtraPrinting.PdfPermissionsOptions.PrintingPermissions : return "Разрешения печати";
            //case DevExpress.XtraPrinting.PdfPasswordSecurityOptions.PermissionsOptions : return "Настройки разрешений";
            //case DevExpress.XtraPrinting.PdfPasswordSecurityOptions.OpenPassword : return "Пароль на открытие";
            //case DevExpress.XtraPrinting.PdfExportOptions.PasswordSecurityOptions : return "Настройки безопасности";
            //case DevExpress.XtraPrinting.PdfPermissionsOptions : return "Настройки разрешений Pdf";
            //case DevExpress.XtraPrinting.PdfPermissionsOptions.EnableScreenReaders : return "Разрешить считывание с экрана";
            //case DevExpress.XtraPrinting.PdfPermissionsOptions.EnableCoping : return "Разрешить копирование";
            //case DevExpress.XtraPrinting.PdfPasswordSecurityOptions : return "Настройки безопасности Pdf";
            //case DevExpress.XtraPrinting.PdfPasswordSecurityOptions.PdfPermissionsOptions : return "Настройки разрешений Pdf";

            default:
                retPrintLocal = String.Empty;
                break;
        }
        return retPrintLocal;
    }
}
