using System;
using DevExpress.XtraGrid.Localization;

public class RussianGridLocalizer : GridLocalizer
{
    public override string Language { get { return "Russian"; } }
    public override string GetLocalizedString(GridStringId id)
    {
        switch (id)
        {
            case GridStringId.EditFormUpdateButton: return "Сохранить";
            case GridStringId.EditFormCancelButton: return "Отмена";
            case GridStringId.EditFormCancelMessage: return "Отменить редактирование?";
            case GridStringId.EditFormSaveMessage: return "Данные изменены. Сохранить изменения?";

            case GridStringId.FindControlFindButton: return "Поиск";
            case GridStringId.FindControlNextButton: return "Далее";
            case GridStringId.FindControlPrevButton: return "Назад";
            case GridStringId.FindNullPrompt: return "Введите текст для поиска...";
            case GridStringId.FileIsNotFoundError: return "Файл {0} не найден";
            case GridStringId.ColumnViewExceptionMessage: return " Хотите исправить значение?";
            case GridStringId.CustomizationCaption: return "Выбор колонок";
            case GridStringId.CustomizationColumns: return "Колонки";
            case GridStringId.CustomizationBands: return "Категории";
            case GridStringId.PopupFilterAll: return "(Все)";
            case GridStringId.PopupFilterCustom: return "(Условие...)";
            case GridStringId.PopupFilterBlanks: return "(Пустые)";
            case GridStringId.PopupFilterNonBlanks: return "(Непустые)";
            case GridStringId.CustomFilterDialogFormCaption: return "Пользовательский автофильтр";
            case GridStringId.CustomFilterDialogCaption: return "Показать только те строки, значения которых:";
            case GridStringId.CustomFilterDialogRadioAnd: return "И";
            case GridStringId.CustomFilterDialogRadioOr: return "ИЛИ";
            case GridStringId.CustomFilterDialogOkButton: return "OK";
            case GridStringId.CustomFilterDialogClearFilter: return "Очистить фильтр";
            case GridStringId.CustomFilterDialogCancelButton: return "Отмена";
            case GridStringId.CustomFilterDialog2FieldCheck: return "Колонка";
            case GridStringId.CustomFilterDialogEmptyValue: return "(Введите значение)";
            case GridStringId.CustomFilterDialogEmptyOperator: return "(Выберите оператор)";
            case GridStringId.CustomFilterDialogHint: return "Используйте _ для представления любого одиночного символа#Используйте % для представления любой последовательности символов";
            case GridStringId.MenuFooterSum: return "Сумма";
            case GridStringId.MenuFooterMin: return "Минимум";
            case GridStringId.MenuFooterMax: return "Максимум";
            case GridStringId.MenuFooterCount: return "Количество";
            case GridStringId.MenuFooterAverage: return "Среднее";
            case GridStringId.MenuFooterNone: return "Нет";
            case GridStringId.MenuFooterSumFormat: return "Сумма={0:#.##}";
            case GridStringId.MenuFooterMinFormat: return "Минимум={0}";
            case GridStringId.MenuFooterMaxFormat: return "Максимум={0}";
            case GridStringId.MenuFooterCountFormat: return "{0}";
            case GridStringId.MenuFooterCountGroupFormat: return "Кол-во={0}";
            case GridStringId.MenuFooterAverageFormat: return "Среднее={0:#.##}";
            case GridStringId.MenuFooterCustomFormat: return "Условие={0}";
            case GridStringId.MenuColumnSortAscending: return "Сортировка по возрастанию";
            case GridStringId.MenuColumnSortDescending: return "Сортировка по убыванию";
            case GridStringId.MenuColumnRemoveColumn: return "Скрыть колонку";
            case GridStringId.MenuColumnShowColumn: return "Показать колонку";
            case GridStringId.MenuColumnClearSorting: return "Очистить сортировку";
            case GridStringId.MenuColumnGroup: return "Группировать по этой колонке";
            case GridStringId.FilterPanelCustomizeButton: return "Конструктор фильтра...";
            case GridStringId.MenuColumnUnGroup: return "Разгруппировать";
            case GridStringId.MenuColumnColumnCustomization: return "Выбор колонок";
            case GridStringId.MenuColumnBestFit: return "Подбор ширины";
            case GridStringId.MenuColumnFilter: return "Фильтр";
            case GridStringId.MenuColumnShowAutoFilter: return "Показать фильтр колонки";
            case GridStringId.MenuColumnFilterEditor: return "Конструктор фильтра...";
            case GridStringId.MenuColumnClearFilter: return "Очистить фильтр";
            case GridStringId.MenuColumnBestFitAllColumns: return "Подбор ширины (все колонки)";
            case GridStringId.MenuColumnResetGroupSummarySort: return "Очистить сортировку по итогам";
            case GridStringId.MenuColumnGroupSummarySortFormat: return "{1} - '{0}' - {2}";
            case GridStringId.MenuColumnSortGroupBySummaryMenu: return "Сортировка по итогам";
            case GridStringId.MenuColumnGroupIntervalMenu: return "Интервал группы";
            case GridStringId.MenuColumnGroupIntervalNone: return "Нет";
            case GridStringId.MenuColumnGroupIntervalDay: return "День";
            case GridStringId.MenuColumnGroupIntervalMonth: return "Месяц";
            case GridStringId.MenuColumnGroupIntervalYear: return "Год";
            case GridStringId.MenuColumnGroupIntervalSmart: return "Умный";
            case GridStringId.MenuColumnGroupSummaryEditor: return "Редактор итога группы...";
            case GridStringId.MenuColumnExpressionEditor: return "Редактор выражения...";
            case GridStringId.MenuColumnConditionalFormatting: return "Условное форматирование";
            case GridStringId.MenuColumnConditionalFiltering: return "Условная фильтрация";
            case GridStringId.MenuGroupRowExpand: return "Раскрыть";
            case GridStringId.MenuGroupRowCollapse: return "Свернуть";
            case GridStringId.MenuGroupPanelFullExpand: return "Раскрыть группы";
            case GridStringId.MenuGroupPanelFullCollapse: return "Свернуть группы";
            case GridStringId.MenuGroupPanelClearGrouping: return "Разгруппировать";
            case GridStringId.PrintDesignerBandedView: return "Настройка печати (Таблица с категориями)";
            case GridStringId.PrintDesignerGridView: return "Настройка печати (Таблица)";
            case GridStringId.PrintDesignerCardView: return "Настройка печати (Карточки)";
            case GridStringId.PrintDesignerBandHeader: return "Категория";
            case GridStringId.PrintDesignerDescription: return "Настроить опции печати для текущего представления.";
            case GridStringId.MenuColumnGroupBox: return "Область группировки";
            case GridStringId.CardViewNewCard: return "Новая карточка";
            case GridStringId.CardViewQuickCustomizationButton: return "Настроить";
            case GridStringId.CardViewQuickCustomizationButtonFilter: return "Фильтр";
            case GridStringId.CardViewQuickCustomizationButtonSort: return "Сортировать:";
            case GridStringId.CardViewCaptionFormat: return "Карточка № {0}";
            case GridStringId.GridGroupPanelText: return "Поместите сюда заголовок колонки для группировки по этой колонке";
            case GridStringId.GridNewRowText: return "Нажмите сюда, чтобы добавить новую строку";
            case GridStringId.FilterBuilderOkButton: return "OK";
            case GridStringId.FilterBuilderCancelButton: return "Отмена";
            case GridStringId.FilterBuilderApplyButton: return "Применить";
            case GridStringId.FilterBuilderCaption: return "Конструктор фильтра";
            case GridStringId.GridOutlookIntervals: return "Раньше;В прошлом месяце;Ранее в этом месяце;Три недели назад;Две недели назад;На прошлой неделе;;;;;;;;Вчера;Сегодня;Завтра;;;;;;;;На следующей неделе;Через две недели;Через три недели;Позднее в этом месяце;В следующем месяце;Позже,чем через месяц;";
            case GridStringId.CustomizationFormColumnHint: return "Перетащите колонки для настройки расположения ";
            case GridStringId.CustomizationFormBandHint: return "Перетащите полосы для настройки расположения ";
            case GridStringId.LayoutViewCloseZoomBtnHintClose: return "Восстановить изображение";
            case GridStringId.LayoutViewCloseZoomBtnHintZoom: return "Детализировать";
            case GridStringId.LayoutViewColumnModeBtnHint: return "Один столбец";
            case GridStringId.LayoutViewMultiColumnModeBtnHint: return "Много столбцов";
            case GridStringId.LayoutViewMultiRowModeBtnHint: return "Много строк";
            case GridStringId.LayoutViewPanBtnHint: return "Панорамирование";
            case GridStringId.LayoutViewRowModeBtnHint: return "Одна строка";
            case GridStringId.LayoutViewSingleModeBtnHint: return "Одна карточка";
            case GridStringId.LayoutViewCarouselModeBtnHint: return "Карусельный режим";
            case GridStringId.LayoutViewCustomizeBtnHint: return "Настройка";
            case GridStringId.LayoutViewButtonApply: return "Применить";
            case GridStringId.LayoutViewButtonCustomizeHide: return "Скрыть настройку";
            case GridStringId.LayoutViewButtonCustomizeShow: return "Показать настройку";
            case GridStringId.LayoutViewButtonLoadLayout: return "Загрузить размещение...";
            case GridStringId.LayoutViewButtonPreview: return "Показать больше карточек";
            case GridStringId.LayoutViewButtonReset: return "Загрузить карточку-шаблон";
            case GridStringId.LayoutViewButtonSaveLayout: return "Сохранить размещение";
            case GridStringId.LayoutViewButtonShrinkToMinimum: return "Сжать карточку-шаблон";
            case GridStringId.LayoutViewGroupCards: return "Карточки";
            case GridStringId.LayoutViewGroupFields: return "Поля";
            case GridStringId.LayoutViewGroupCaptions: return "Заголовки";
            case GridStringId.LayoutViewGroupCustomization: return "Настройка";
            case GridStringId.LayoutViewGroupHiddenItems: return "Скрыть элементы";
            case GridStringId.LayoutViewGroupIndents: return "Отступ";
            case GridStringId.LayoutViewGroupTreeStructure: return "Расположение дерева";
            case GridStringId.LayoutViewGroupIntervals: return "Интервалы";
            case GridStringId.LayoutViewLabelAllowFieldHotTracking: return "Отслеживание в реальном времени";
            case GridStringId.LayoutViewLabelCaptionLocation: return "Размещение заголовка:";
            case GridStringId.LayoutViewLabelCardArrangeRule: return "Упорядочить правила:";
            case GridStringId.LayoutViewLabelCardEdgeAlignment: return "Выравнивание границы карточки:";
            case GridStringId.LayoutViewLabelGroupCaptionLocation: return "Размещение заголовка группы:";
            case GridStringId.LayoutViewLabelHorizontal: return "Горизонтальный интервал";
            case GridStringId.LayoutViewLabelPadding: return "Заполнение";
            case GridStringId.LayoutViewLabelScrollVisibility: return "Видимость полосы прокрутки:";
            case GridStringId.LayoutViewLabelShowCardBorder: return "Показать границу";
            case GridStringId.LayoutViewLabelShowCardCaption: return "Показать заголовок";
            case GridStringId.LayoutViewLabelShowCardExpandButton: return "Показать кнопку расширения";
            case GridStringId.LayoutViewLabelShowFieldBorder: return "Показать границу";
            case GridStringId.LayoutViewLabelShowFieldHint: return "Показать подсказку";
            case GridStringId.LayoutViewLabelShowFilterPanel: return "Показать панель фильтра";
            case GridStringId.LayoutViewLabelShowHeaderPanel: return "Показать панель заголовка";
            case GridStringId.LayoutViewLabelShowLines: return "Показать линии";
            case GridStringId.LayoutViewLabelSpacing: return "Расстановка";
            case GridStringId.LayoutViewLabelTextAlignment: return "Выравнивание текста заголовка поля:";
            case GridStringId.LayoutViewLabelTextIndent: return "Замещение текста";
            case GridStringId.LayoutViewLabelVertical: return "Вертикальный интервал";
            case GridStringId.LayoutViewLabelViewMode: return "Режим просмотра:";
            case GridStringId.LayoutViewGroupLayout: return "Расположение";
            case GridStringId.LayoutViewPageTemplateCard: return "Шаблон карточки";
            case GridStringId.LayoutViewPageViewLayout: return "Вид расположения";
            case GridStringId.LayoutViewGroupView: return "Вид";
            case GridStringId.PrintDesignerLayoutView: return "Настройки печати( Вид расположения)";
            case GridStringId.LayoutViewGroupPropertyGrid: return "Редактор свойств";
            case GridStringId.LayoutViewCustomizationFormCaption: return "Настройка вида расположения";
            case GridStringId.LayoutViewButtonCancel: return "Отмена";
            case GridStringId.LayoutViewButtonOk: return "ОК";
            case GridStringId.LayoutViewCustomizationFormDescription: return "Настройка расположения карточки путем перетаскивания и меню настройки, и просмотр данных в окне настройке расположения";
            case GridStringId.LayoutModifiedWarning: return "Расположение было изменено";
            case GridStringId.LayoutViewCardCaptionFormat: return "Карточка [{0} из {1}]";
            case GridStringId.LayoutViewFieldCaptionFormat: return "{0}:";
            case GridStringId.MenuColumnSumSummaryTypeDescription: return "Сумма";
            case GridStringId.MenuColumnMinSummaryTypeDescription: return "Минимум";
            case GridStringId.MenuColumnMaxSummaryTypeDescription: return "Максимум";
            case GridStringId.MenuColumnCountSummaryTypeDescription: return "Количество";
            case GridStringId.MenuColumnAverageSummaryTypeDescription: return "Среднее";
            case GridStringId.MenuGroupPanelShow: return "Показать область группировки";
            case GridStringId.MenuGroupPanelHide: return "Скрыть область группировки";
            case GridStringId.GroupSummaryEditorFormCaption: return "Редактор итога группы";
            case GridStringId.GroupSummaryEditorFormOkButton: return "ОК";
            case GridStringId.GroupSummaryEditorFormCancelButton: return "Отмена";
            case GridStringId.GroupSummaryEditorFormItemsTabCaption: return "Элементы";
            case GridStringId.GroupSummaryEditorFormOrderTabCaption: return "Порядок";
            case GridStringId.GroupSummaryEditorSummaryMin: return "Минимум";
            case GridStringId.GroupSummaryEditorSummaryMax: return "Максимум";
            case GridStringId.GroupSummaryEditorSummaryAverage: return "Среднее";
            case GridStringId.GroupSummaryEditorSummarySum: return "Сумма";
            case GridStringId.GroupSummaryEditorSummaryCount: return "Количество";
            case GridStringId.WindowErrorCaption: return "Ошибка";
            case GridStringId.SearchLookUpMissingRows: return "Нажмите ENTER или Поиск, чтобы отобразить все строки. Введите текст и нажмите ENTER для поиска по строкам.";
            case GridStringId.MenuColumnFilterModeDisplayText: return "Отображаемый текст";
            case GridStringId.MenuColumnFindFilterHide: return "Скрыть панель поиска";
            case GridStringId.MenuColumnFilterModeValue: return "Значение";
            case GridStringId.MenuColumnAutoFilterRowHide: return "Скрыть строку авто-фильтра";
            case GridStringId.MenuColumnFindFilterShow: return "Показать панель поиска";
            case GridStringId.MenuColumnAutoFilterRowShow: return "Показать строку авто-фильтра";
            case GridStringId.MenuColumnFilterMode: return "Режим фильтра";
            case GridStringId.MenuColumnClearAllSorting: return "Очистить всю сортировку";
            case GridStringId.FindControlClearButton: return "Очистить";
            case GridStringId.SearchLookUpAddNewButton: return "Добавить новый";
            case GridStringId.MenuColumnBandCustomization: return "Выбор колонок и категорий";
            case GridStringId.MenuColumnCustomSummaryTypeDescription: return "Пользовательское";
            case GridStringId.MenuFooterAddSummaryItem: return "Добавить новую сумму";
            case GridStringId.MenuFooterClearSummaryItems: return "Очистить элементы";
            case GridStringId.MenuShowSplitItem: return "Разделить";
            case GridStringId.MenuHideSplitItem: return "Убрать разделение";
            case GridStringId.MenuFooterShow: return "Показать футер";
            case GridStringId.MenuFooterHide: return "Скрыть футер";
            case GridStringId.MenuFooterMode: return "Режим";
            case GridStringId.MenuFooterAllRows: return "Все строки";
            case GridStringId.MenuFooterSelection: return "Выделение";
            case GridStringId.MenuFooterMixed: return "Смешанный";
            default:
                return base.GetLocalizedString(id);
        }
    }
}

