using System;

namespace SewingProduction.Features.CuttingProduction.Models
{
    public class raskrZehUpView
    {
        public int? PR_CRPT { get; set; }
        public decimal? nom { get; set; }
        public decimal? nom_n { get; set; }
        public decimal? n_pach { get; set; }
        public DateTime? data_r { get; set; }
        public string kod { get; set; }
        public string po { get; set; }
        public string grup { get; set; }
        public string articul { get; set; }
        public string mod { get; set; }
        public string razm { get; set; }
        public decimal? kol { get; set; }
        public decimal? kol2 { get; set; }
        public DateTime? data_pr { get; set; }
        public DateTime? data_v { get; set; }
        public int? tab_r1 { get; set; }
        public string fio1 { get; set; }
        public int? tab_r2 { get; set; }
        public string fio2 { get; set; }
        public int? tab_p { get; set; }
        public string fio_p { get; set; }
        public string n_zvet { get; set; }
        public decimal? n_zeh { get; set; }
        public decimal? n_zeh_kr { get; set; }
        public decimal? mest_zeh { get; set; }
        public string po_zeh { get; set; }
        public DateTime? data_zeh { get; set; }
        public string dost_zeh { get; set; }
        public DateTime? data_zeh_p { get; set; }
        public DateTime? data_rab { get; set; }
        public DateTime? data_up { get; set; }
        public DateTime? data_up_p { get; set; }
        public int? tab_up { get; set; }
        public DateTime? data_cd { get; set; }
        public decimal? po_o_st { get; set; }
        public string po_o { get; set; }
        public DateTime? data_o { get; set; }
        public string pach_kod { get; set; }
        public decimal? god { get; set; }
        public decimal? iz_nakl { get; set; }
        public string iz { get; set; }
        public DateTime? iz_data { get; set; }
        public decimal? n_f { get; set; }
        public DateTime? data_f_o { get; set; }
        public DateTime? data_f_z { get; set; }
        public decimal? n_f_u { get; set; }
        public DateTime? data_f_o_u { get; set; }
        public DateTime? data_f_z_u { get; set; }
        public string fio_v1 { get; set; }
        public string fio_v2 { get; set; }
        public decimal? vipad { get; set; }
        public string tr { get; set; }
        public string kod_k { get; set; }
        public string grup_k { get; set; }
        public string articul_k { get; set; }
        public string mod_k { get; set; }
        public string razm_k { get; set; }
        public DateTime? data_plan { get; set; }
        public DateTime? data_pr_p { get; set; }
        public DateTime? data_v_p { get; set; }
        public DateTime? data_pr_cd { get; set; }
        public DateTime? data_v_cd { get; set; }
        public DateTime? data_v_r { get; set; }
        public DateTime? data_pr_r { get; set; }
        public DateTime? data_r_pr { get; set; }
        public string txt { get; set; }
        public string nom_zad { get; set; }
        public string tr_mb { get; set; }
        public string sez { get; set; }
        public int? tab_k { get; set; }
        public int? tab_m { get; set; }
        public int? tab_t { get; set; }
        public DateTime? data_rasv { get; set; }
        public DateTime? data_rasp { get; set; }
        public DateTime? data_rash { get; set; }
        public DateTime? data_vozh { get; set; }
        public DateTime? data_sozd { get; set; }
        public int? tab_buh { get; set; }
        public int? tab_kpv { get; set; }
        public decimal? kol_hi_r { get; set; }
        public decimal? kol_hi_br { get; set; }
        public decimal? n_rasv { get; set; }
        public decimal? n_rasp { get; set; }
        public decimal? n_rascd { get; set; }
        public decimal? n_pras { get; set; }
        public decimal? n_pv { get; set; }
        public decimal? n_vras { get; set; }
        public decimal? v { get; set; }
        public decimal? kol_v { get; set; }
        public decimal? kol_zv { get; set; }
        public decimal? stra { get; set; }
        public decimal? p { get; set; }
        public decimal? kol_p { get; set; }
        public decimal? p_seb { get; set; }
        public string p_po { get; set; }
        public decimal? p_tamp { get; set; }
        public decimal? poet { get; set; }
        public decimal? laz { get; set; }
        public decimal? stir { get; set; }
        public decimal? stra_seb { get; set; }
        public decimal? v_seb { get; set; }
        public DateTime? data_st_p { get; set; }
        public DateTime? data_st_r { get; set; }
        public DateTime? data_st_cd { get; set; }
        public decimal? vsh { get; set; }
        public string skl_koo { get; set; }
        public DateTime? skl_data { get; set; }
        public decimal? skl_otgr { get; set; }
        public string mg_zakr { get; set; }
        public DateTime? data_cd_ut { get; set; }
        public DateTime? data_rst { get; set; }
        public decimal? h_reestr { get; set; }
        public decimal? vidr { get; set; }
        public decimal? kod_stir { get; set; }
        public DateTime? data_stir { get; set; }
        public int? tab_stir1 { get; set; }
        public int? tab_stir2 { get; set; }
        public string kle { get; set; }
        public int? nomer_rasp { get; set; }
        public DateTime? data_raspb { get; set; }
        public DateTime? data_na_sk { get; set; }
        public decimal? mest_na_sk { get; set; }
        public DateTime? data_so_sk { get; set; }
        public decimal? mest_so_sk { get; set; }
        public string koord { get; set; }
        public DateTime? data_pr_ut { get; set; }
        public int? nom_m15 { get; set; }
        public decimal? pr_printer { get; set; }
        public decimal? pr_format { get; set; }
        public DateTime? data_sk_zp { get; set; }
        public DateTime? data_pt { get; set; }
        public decimal? kol_uvs2 { get; set; }
        public DateTime? data_p { get; set; }
        public int? tab_klad { get; set; }
        public DateTime? data_klad { get; set; }
        public DateTime? data_buh { get; set; }
        public DateTime? vygr_1c { get; set; }
        public DateTime? data_1c { get; set; }
        public string nom_zak { get; set; }
        public string kod_sh_1c { get; set; }
        public int? id_order { get; set; }
        public DateTime? d_kontr_ml { get; set; }
        public DateTime? datzakrprn { get; set; }
        public string nomdocprn { get; set; }
        public decimal? printer { get; set; }
        public DateTime? data_pr_pe { get; set; }
        public DateTime? data_v_chi { get; set; }
        public decimal? bus { get; set; }
        public decimal? bus_seb { get; set; }
        public decimal? gofp { get; set; }
        public decimal? p_pres { get; set; }
        public string nom_all { get; set; }
        public decimal? zvet_all { get; set; }
        public decimal? nabiv_all { get; set; }
        public int? skl_id_1c { get; set; }
        public int? id_brig { get; set; }
        public DateTime? data_1c_wh { get; set; }
        public decimal? term { get; set; }
        public decimal? term_seb { get; set; }
        public int? tab_ork { get; set; }
        public DateTime? data_kk_cd { get; set; }
        public DateTime? data_dubcd { get; set; }
        public DateTime? data_pr_km { get; set; }
        public int? bd { get; set; }
        public int? dtf_print { get; set; }
        public string? fio_ork { get; set; }
        public string? fio_k { get; set; }
        public bool HasDatePr => data_pr.HasValue;
        public bool HasDatePt => data_pt.HasValue;
        public bool HasDateV => data_v.HasValue;
        public int groupIndex { get; set; }
        public string PachYear => $"{n_pach}{data_r.Value.Year}";
        public int rz_id { get; set; }
    }
}
